### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by KunwarSiddharthSingh** [sonata-project/ecommerce#16]
When I write route in routing,yml as doc:

```
sonata_order:
    resource: @SonataOrderBundle/Resources/config/routing/order.xml
    prefix: /shop/user/invoice

sonata_product:
    resource: @SonataProductBundle/Resources/config/routing/product.xml
    prefix: /shop/product   

sonata_category:
    resource: @SonataProductBundle/Resources/config/routing/category.xml
    prefix: /shop/category

sonata_payment:
    resource: @SonataPaymentBundle/Resources/config/routing/payment.xml
    prefix: /shop/payment

sonata_invoice:
    resource: @SonataInvoiceBundle/Resources/config/routing/invoice.xml
    prefix: /shop/user/invoice
```

Only /shop/category url working and others url not working.

I do not know why ?

All configuration is right as per doc.

Any Suggestion will be highly appreciated..!!
