### ISSUE TITLE
Can't see my custom delivery method

### ISSUE THREAD

**Issue by lucassimonin** [sonata-project/ecommerce#346]
Hi everyone,

I add a new delivery method like this :
sonata_delivery:
    selector: sonata.delivery.selector.default

```
services:
    free_address_required:
        name: Free
        priority: 10
        code: free

methods:
    free: ~
    chronopost: sonata.delivery.method.chronopost
```

But when I want to add to my product I see only the Free method delivery

Can you help me ?

Thank
