### ISSUE TITLE
Can't add own Payment Method?

### ISSUE THREAD

**Issue by SantoDE** [sonata-project/ecommerce#357]
Hey fellas,

I'm currently trying to add a new payment method to my project. I followed your docs and placed that within my sonata_payment.yml below the sonata_payment.services block:

```yaml
concardis:
            name:    Concardis
            code:    concardis
            browser: sonata.payment.browser.curl
            enabled: true

            transformers:
                basket: sonata.payment.transformer.basket
                order:  sonata.payment.transformer.order
```

However, I only end up having this exception:

>   [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
>   Unrecognized option "concardis" under "sonata_payment.services"

Anyone got an idea? Thanks :)
